[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -kernel"

rustflags = [
"-C", "link-args=-Tlink.ld boot.elf64.o",
]

[target.i686-unknown-none]
runner = "qemu-system-i386 -kernel"

rustflags = [
"-C", "link-args=-Tlink.ld boot.elf32.o",
]

[build]
# target = "x86_64-unknown-none.json"
target = "i686-unknown-none.json"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]
